### PR TITLE
Fix file headers and footer for ELPA compatibility

### PR DESCRIPTION
**Pull request by purcell**
I'm creating a [MELPA](http://melpa.milkbox.net/) recipe for this, and the headers/footers aren't compatible with package.el -- this commit fixes them.

BTW, if you look at the latest version of [flymake-ruby](http://github.com/purcell/flymake-ruby), you'll see that I've simplified it further using my [flymake-easy](http://github.com/purcell/flymake-easy) helpers.

### CODE REVIEW

**Comment by sroccaserra** [comment]
Thanks, I'll look into flymake-easy.

Cheers!
Sébastien.

**Comment by purcell** [comment]
Ah, crap: the first line needed 3 dashes, not 2, ie. 

```
;;; flymake-lua.el --- Flymake for Lua
```

Can you maybe add the missing dash please?

-Steve

**Comment by sroccaserra** [comment]
Done !

**Comment by purcell** [comment]
Thanks!

**Pull request merged**
